FROM lsqtzj/openeuler_httpd AS base

EXPOSE 80

WORKDIR /opt
RUN yum update -y
RUN yum -y install shadow-utils libxslt libzip libcurl oniguruma re2c libmcrypt mhash 

FROM base AS builder

RUN yum -y install wget tar make gcc autoconf systemd-devel openjpeg2-devel gcc-c++ \
        pcre-devel zlib-devel libxml2 libxml2-devel openssl openssl-devel bzip2 bzip2-devel \
        libcurl libcurl-devel libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel \
        gmp gmp-devel readline readline-devel libxslt libxslt-devel sqlite-devel bison \
        enchant automake libtool libedit libedit-devel oniguruma oniguruma-devel libzip libzip-devel \
        enchant enchant-devel libicu libicu-devel libldb openldap openldap-devel libaio krb5-devel

RUN wget https://www.openssl.org/source/openssl-1.1.1l.tar.gz && \
    tar -xzvf openssl-1.1.1l.tar.gz && \
    cd openssl-1.1.1l && ./config --prefix=/usr/local/openssl && make && make install

RUN wget https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz
RUN tar -zvxf libiconv-*.tar.gz && rm -Rf libiconv-*.tar.gz
RUN cd libiconv-* && ./configure --prefix=/usr/local/libiconv && make -j4 && make install

ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH:/usr/local/libiconv/lib:/usr/local/openssl/lib
RUN ldconfig

RUN wget https://www.php.net/distributions/php-7.3.0.tar.bz2
RUN tar -xvf php-*.tar.bz2 && rm -Rf php-*.tar.bz2
RUN yum -y install mysql-devel
RUN cd /opt/php-* && \
        ./configure \
        --prefix=/usr/local/php \
        --with-config-file-path=/usr/local/php/etc \
        --with-iconv-dir=/usr/local/libiconv \
        --with-fpm-user=www \
        --with-fpm-group=www \
        --enable-fpm \
        --enable-opcache=no \
        --with-pdo-mysql=mysqlnd \
        --with-curl	\
        --with-zlib \
        --with-zlib-dir \
        --with-libxml-dir \
        --with-freetype-dir \
        --with-jpeg-dir \
        --with-png-dir \
        --with-curl \
        --with-gettext \
        --with-kerberos \
        --with-libdir=lib64 \
        --with-mysqli \
        --with-pdo-mysql \
        --with-pdo-sqlite \
        --with-pear \
        --with-xmlrpc \
        --with-xsl \
        --with-zlib \
        --with-zlib-dir \
        --with-bz2 \
        --with-mhash \
        --enable-bcmath \
        --enable-inline-optimization \
        --enable-mbregex \
        --enable-mbstring \
        --enable-opcache \
        --enable-pcntl \
        --enable-shmop \
        --enable-soap \
        --enable-sockets \
        --enable-sysvsem \
        --enable-sysvshm \
        --enable-xml \
        --with-apxs2 && make -j4 ZEND_EXTRA_LIBS='-liconv' && make install

RUN wget https://github.com/legale/phpenmod/raw/master/phpenmod -O /bin/phpenmod && chmod +x /bin/phpenmod
RUN wget https://getcomposer.org/download/latest-stable/composer.phar

RUN sed -i '/<Directory "\/var\/www\/html">/a\    AddType application\/x-httpd-php .php' /etc/httpd/conf/httpd.conf
RUN sed -i '/LoadModule rewrite_module lib64\/httpd\/modules\/mod_rewrite.so/a LoadModule php7_module lib64\/httpd\/modules\/libphp7.so' /etc/httpd/conf/httpd.conf
RUN sed -i 's/DirectoryIndex index.html/DirectoryIndex index.php index.html/g' /etc/httpd/conf/httpd.conf
COPY  ./php/php.ini /usr/local/php/etc/php.ini
COPY  ./php/php-fpm.conf  /usr/local/php/etc/php-fpm.conf
FROM base AS runtime
RUN yum -y install shadow-utils freetype libjpeg libpng libwebp libXpm libzip libicu
COPY --from=builder /usr/local/php  /usr/local/php
COPY --from=builder /usr/local/openssl /usr/local/openssl
COPY --from=builder /usr/local/libiconv /usr/local/libiconv
COPY --from=builder /usr/lib64/httpd /usr/lib64/httpd
COPY --from=builder /etc/httpd /etc/httpd
COPY --from=builder /opt/composer.phar /usr/bin/composer

RUN     ln -s /usr/local/php/bin/php /usr/bin/php;\
        ln -s /usr/local/php/bin/phpize /usr/bin/phpize;\
        ln -s /usr/local/php/sbin/php-fpm /usr/bin/php-fpm;
RUN chmod 755 /usr/local/php/etc/php-fpm.conf && chmod 755 /usr/local/php/etc/php.ini

RUN chmod -R 777 /usr/bin/composer
RUN composer config -g -- disable-tls true
COPY ./php/auth.json /root/.config/composer/auth.json
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/libiconv/lib:/usr/local/openssl/lib
ENV PATH=$PATH:/usr/local/openssl/bin/:/usr/local/php/sbin:/usr/local/php/bin:/usr/local/libiconv/bin

ENTRYPOINT [ "/opt/main.sh"]
CMD ["/bin/bash"]